version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prosigliere
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  migrate:
    image: flyway/flyway:10
    container_name: flyway-migrate
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./cmd/migration:/flyway/sql
      - ./cmd/migration/config:/flyway/conf

    command: >
      -url=jdbc:postgresql://db:5432/prosigliere
      -user=postgres
      -password=postgres
      migrate
    restart: "no"

  api:
    build: .
    container_name: prosigliere-api
    depends_on:
      - db
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  pgdata:
